[project]
name = "pomodoro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.0",
    "pillow>=11.1.0",
    "pyinstaller>=6.12.0",
    "pyqt5>=5.15.11",
]
